version: 0.1

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn install
  pre_build:
    commands:
      - yarn docs
  build:
    commands:
      - yarn build
      - VERSION=$(node -e "console.log(require('./package.json').version)")
      - [ $STAGE -eq 'prod' ]; then aws s3 rm --recursive s3://dragonchain-sdk-node-docs/latest/*
      - [ $STAGE -eq 'prod' ]; then aws s3 cp --recursive ./docs s3://dragonchain-sdk-node-docs/latest
      - [ $STAGE -eq 'prod' ]; then aws s3 rm --recursive s3://dragonchain-sdk-node-docs/$VERSION/*
      - [ $STAGE -eq 'prod' ]; then aws s3 cp --recursive ./docs s3://dragonchain-sdk-node-docs/$VERSION/

