version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn install
  pre_build:
    commands:
      - yarn integration
  build:
    commands:
      - yarn build
      - API_KEY=$API_KEY yarn integration
  #     # deploy to NPM
  #     - VERSION=$(node -e "console.log(require('./package.json').version)")
  #     - aws cp --recursive ./docs/* s3://dragonchain-sdk-node-docs/latest
  #     - aws cp --recursive ./docs/* s3://dragonchain-sdk-node-docs/$VERSION

