version: 0.1

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn install
  pre_build:
    commands:
      - yarn test
  # build:
  #   commands:
  #     - yarn build
      # - publish to NPM

