version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn install
      # - apt-get update
      # - apt-get install jq=1.5+dfsg-1ubuntu0.1
  build:
    commands:
      - VERSION=$(node -e "console.log(require('./package.json').version)")
      - yarn build
      - npm config set '//registry.npmjs.org/:_authToken' $(aws ssm get-parameter --name npm-publish-token --with-decryption | jq '.Parameter.Value')
      - npm publish --access restricted
      - yarn docs
      - aws s3 rm --recursive s3://dragonchain-sdk-node-docs/latest/*
      - aws s3 cp --recursive ./docs s3://dragonchain-sdk-node-docs/latest
      - aws s3 rm --recursive s3://dragonchain-sdk-node-docs/$VERSION/*
      - aws s3 cp --recursive ./docs s3://dragonchain-sdk-node-docs/$VERSION/
