version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn install
      # - apt-get update
      # - apt-get install jq=1.5+dfsg-1ubuntu0.1
      # - brew install --HEAD jq
      # - wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
      # - chmod +x jq-linux64
      # - mv jq-linux64 $(which jq)
  pre_build:
    commands:
      # - yarn integration
  build:
    commands:
      - yarn build
      # - export AUTH_KEY=$(aws secretsmanager get-secret-value --secret-id dragonchain-sdk-integration-key | jq '.SecretString' | jq fromjson | jq '.AUTH_KEY')
      # - export AUTH_KEY_ID=$(aws secretsmanager get-secret-value --secret-id dragonchain-sdk-integration-key | jq '.SecretString' | jq fromjson | jq '.AUTH_KEY_ID')
      # - yarn integration

