version: 0.2

phases:
  install:
    commands:
      - npm install -g yarn
      - yarn install
      - apt-get update
      - apt-get install jq
  build:
    commands:
      - VERSION=$(node -e "console.log(require('./package.json').version)")
      - yarn build
      - if [ "$STAGE" == 'prod' ]; then export NPM_TOKEN=$(aws secretsmanager get-secret-value --secret-id npm/publish/token | jq -r '.SecretString' | jq -r '.NPM_TOKEN'); fi
      - if [ "$STAGE" == 'prod' ]; then npm publish --access restricted; fi
      - yarn docs
      - if [ "$STAGE" == 'prod' ]; then aws s3 rm --recursive s3://dragonchain-sdk-node-docs/latest/*; fi
      - if [ "$STAGE" == 'prod' ]; then aws s3 cp --recursive ./docs s3://dragonchain-sdk-node-docs/latest; fi
      - if [ "$STAGE" == 'prod' ]; then aws s3 rm --recursive s3://dragonchain-sdk-node-docs/$VERSION/*; fi
      - if [ "$STAGE" == 'prod' ]; then aws s3 cp --recursive ./docs s3://dragonchain-sdk-node-docs/$VERSION/; fi
